name: javaRunner

on: [ push, pull_request ]
jobs:
  demo31:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk-slim
    steps:
    - uses: actions/checkout@v4
    - name: complie javac
      run: |
          dir
          javac Hello.java
          dir
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: Hello.class
      
  demo32:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk-slim
    needs : demo31
    steps:
    - uses: actions/checkout@v4
    - name: Download  artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: running java
      run : |
          dir
          java Hello
          dir
