name: javaRunner

on: [ push, pull_request ]
jobs:
  demo3:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:      
    - name: running java
      run:
        javac Hello.java
        java Hello
